# cmake/set_g3log.cmake

# ========= g3log build options =========
# 编译模式
set(G3_SHARED_LIB OFF CACHE BOOL "" FORCE)
set(INSTALL_G3LOG OFF CACHE BOOL "" FORCE)

# 排除不需要的内容 (单元测试和示例)
set(ADD_G3LOG_UNIT_TEST OFF CACHE BOOL "" FORCE)
set(ADD_FATAL_EXAMPLE OFF CACHE BOOL "" FORCE)

# 性能与格式
set(USE_DYNAMIC_LOGGING_LEVELS OFF CACHE BOOL "" FORCE)
set(CHANGE_G3LOG_DEBUG_TO_DBUG ON CACHE BOOL "" FORCE)
set(G3_LOG_FULL_FILENAME ON CACHE BOOL "" FORCE)
set(USE_G3_DYNAMIC_MAX_MESSAGE_SIZE OFF CACHE BOOL "" FORCE)


# 异常处理
set(ENABLE_FATAL_SIGNALHANDLING ON CACHE BOOL "" FORCE)
if(WIN32)
    set(ENABLE_VECTORED_EXCEPTIONHANDLING ON CACHE BOOL "" FORCE)
endif()
